config/routes.rb
Depot::Application.routes.draw do
  resources :abouts

  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, :on => :member
    end
    # You can have the root of your site routed with "root"
    # just remember to delete public/index.html.
    # root :to => "welcome#index"
    root :to => 'store#index', :as => 'store'
  end
end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  
  def total_items
    line_items.sum(:quantity)
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base  
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]
  has_many :line_items, :dependent => :destroy
  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES   

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  has_many :line_items
  has_many :orders, :through => :line_items
  #...
  before_destroy :ensure_not_referenced_by_any_line_item


  # validation stuff...
  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
# 
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with    => %r{\.(gif|jpg|png|jpeg)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :title, :length => {:minimum => 10}
  private
    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')       
        return false
      end
    end
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
 
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader   :password

  validate  :password_must_be_present
  
  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end
  
  # 'password' is a virtual attribute
  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end
  
  after_destroy :ensure_an_admin_remains

  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end     

  private

    def password_must_be_present
      errors.add(:password, "Missing password") unless hashed_password.present?
    end
  
    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/controllers/application.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time

  # See ActionController::RequestForgeryProtection for details
  # Uncomment the :secret if you're not using the cookie session store
  protect_from_forgery # :secret => '02cfe707f830d639beeeb647cc97148e'
  
  # See ActionController::Base for details 
  # Uncomment this to filter the contents of submitted sensitive data parameters
  # from your application log (in this case, all fields with names like "password").  
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  skip_before_filter :authorize
  
  def about
  end

end

app/controllers/says_controller.rb
class SaysController < ApplicationController
  skip_before_filter :authorize
  # GET /says
  # GET /says.xml
  def index
    @says = Say.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @says }
    end
  end

  # GET /says/1
  # GET /says/1.xml
  def show
    @say = Say.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @say }
    end
  end

  # GET /says/new
  # GET /says/new.xml
  def new
    @say = Say.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @say }
    end
  end

  # GET /says/1/edit
  def edit
    @say = Say.find(params[:id])
  end

  # POST /says
  # POST /says.xml
  def create
    @say = Say.new(params[:say])

    respond_to do |format|
      if @say.save
        format.html { redirect_to(@say, :notice => 'Say was successfully created.') }
        format.xml  { render :xml => @say, :status => :created, :location => @say }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @say.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /says/1
  # PUT /says/1.xml
  def update
    @say = Say.find(params[:id])

    respond_to do |format|
      if @say.update_attributes(params[:say])
        format.html { redirect_to(@say, :notice => 'Say was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @say.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /says/1
  # DELETE /says/1.xml
  def destroy
    @say = Say.find(params[:id])
    @say.destroy

    respond_to do |format|
      format.html { redirect_to(says_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
   if condition
    attributes["style"] = "display: none"
   end
  content_tag("div", attributes, &block)
end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
<p>You are in the Admin zone.</p>
<p>You can change orders, products and users.</p>
<p>We have <%= pluralize(@total_orders, "order") %>, <%= pluralize(@total_users, "users") %> and <%= pluralize(@total_products, "products") %>.</p>
<p>&nbsp&nbsp</p>
<p>&nbsp&nbsp</p>
It's <%= Time.now %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pragprog Books Online Store</title>
<%= stylesheet_link_tag "scaffold" %>
<%= stylesheet_link_tag "depot", :media => "all" %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
</head>
<body id="store" >
<div id="banner" >
<%= form_tag store_path, :class => 'locale' do %>
<%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), :onchange => 'this.form.submit()' %>
<%= submit_tag 'submit' %>
<%= javascript_tag "$$('.locale input').each(Element.hide)" %>
<% end %>
<%= image_tag("catalog.png") %>
<%= @page_title || t('.title') %>
</div>
<%= @time %>
<div id="columns" >
<div id="side" >
<div id="cart" >
<% if @cart %>
<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
<%= render @cart %>
<% end %>
<% end %>
</div>
<%= link_to  t('.store'),  store_path %><br />
<%= link_to  t('.login'),  users_path %><br />
<%= link_to  t('.about'),  abouts_path %><br />
<% if session[:user_id] %>
<br />
<%= link_to 'Orders', orders_path %><br />
<%= link_to 'Products', products_path %><br />
<%= link_to 'Users', users_path %><br />
<br />
<%= button_to 'Logout', logout_path, :method => :delete %>
<% end %>
</div>
<div id="main" >
<%= yield %>
</div>
</div>
</body>
</html>

app/views/notifier/order_received.text.erb
Notifier: Order received
Dear <%= @order.name %>
Thank you for your recent order from The Pragmatic Store.
You ordered the following items:
<%= render @order.line_items %>
We'll send you a separate e-mail when your order ships.

app/views/notifier/order_shipped.text.erb
Notifier#order_shipped

<h3>Pragmatic Order Shipped</h3>
<p>
This is just to let you know that we've shipped your recent order:
</p>
<table>
<tr><th colspan="2" >Qty</th><th>Description</th></tr>
<%= render @order.line_items %>
</table>